// Generated by scripts/seed-from-samples.ts from samples/expected — do not edit by hand.
import type { Preset } from './roster.ts';

export const SEED_PRESETS: Record<string, Preset[]> = {
 "asmaa-radi": [
  {
   "day": 2,
   "slots": [6, 7],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 3,
   "slots": [2, 3],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 3,
   "slots": [6, 7],
   "type": "lecture",
   "text": "دوائر كهربية والكترونية (ELP 331 )/قاعة 431",
   "course": {
    "key": "external|دوائر كهربيه والكترونيه",
    "name": "دوائر كهربية والكترونية (ELP 331 )",
    "share": 0.5,
    "weeks": "1 - 7"
   }
  },
  {
   "day": 4,
   "slots": [0, 1],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 4,
   "slots": [6, 7, 8, 9],
   "type": "office",
   "text": "ساعات مكتبية"
  }],
 "ahmed-salem": [
  {
   "day": 1,
   "slots": [4, 5],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 1,
   "slots": [8, 9],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 2,
   "slots": [2, 3],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 4,
   "slots": [4, 5, 6, 7],
   "type": "office",
   "text": "ساعات مكتبية"
  }],
 "mai-helmy": [
  {
   "day": 2,
   "slots": [0, 1],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 2,
   "slots": [4, 5, 6],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [0, 1],
   "type": "supervision",
   "text": "اشراف معمل دوائر كهربية و الكترونية"
  },
  {
   "day": 3,
   "slots": [6, 7],
   "type": "lecture",
   "text": "محاضرة دوائر كهربية والكترونية (ELP 331 )/قاعة 431",
   "course": {
    "key": "external|دوائر كهربيه والكترونيه",
    "name": "دوائر كهربية والكترونية (ELP 331 )",
    "share": 0.5,
    "weeks": "9 - 15"
   }
  },
  {
   "day": 3,
   "slots": [8, 9],
   "type": "supervision",
   "text": "اشراف معمل دوائر كهربية و الكترونية"
  },
  {
   "day": 5,
   "slots": [0, 1],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 5,
   "slots": [2, 3],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 5,
   "slots": [6, 7],
   "type": "quality",
   "text": "جودة"
  }],
 "hend-elsayed": [
  {
   "day": 2,
   "slots": [6, 7],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [2, 3],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [6, 7],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 4,
   "slots": [2, 3],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 4,
   "slots": [4, 5],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  }],
 "ahmed-elsayed": [
  {
   "day": 0,
   "slots": [0, 1, 2, 3],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 1,
   "slots": [0, 1],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 2,
   "slots": [6, 7],
   "type": "lecture",
   "text": "محاضرة آلات القوي الكهربية ( ELP 331) مدرج ميكانيكا",
   "course": {
    "key": "external|الات القوي الكهربيه",
    "name": "الات القوى الكهربية ( ELP 331)",
    "share": 0.5,
    "weeks": "1 - 7"
   }
  },
  {
   "day": 3,
   "slots": [6, 7],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 5,
   "slots": [2, 3],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  }],
 "asmaa-abdelrahim": [
  {
   "day": 1,
   "slots": [6, 7],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 1,
   "slots": [9],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 2,
   "slots": [0, 1],
   "type": "lecture",
   "text": "محاضرة حاسبات وبرمجه مدرج 1",
   "course": {
    "key": "external|حاسبات وبرمجه",
    "name": "حاسبات وبرمجه",
    "share": 0.5,
    "weeks": "1 - 7"
   }
  },
  {
   "day": 2,
   "slots": [9],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 3,
   "slots": [3],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [4, 5],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 3,
   "slots": [8, 9],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 5,
   "slots": [0, 1],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 5,
   "slots": [2, 3],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 5,
   "slots": [7, 8],
   "type": "quality",
   "text": "جودة"
  }],
 "mahmoud-elsadd": [
  {
   "day": 0,
   "slots": [4, 5],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 0,
   "slots": [6, 7],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 0,
   "slots": [8, 9],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 1,
   "slots": [0, 1],
   "type": "lecture",
   "text": "محاضرة رياضيات 1 (مدرج 1)",
   "course": {
    "key": "external|رياضيات 1",
    "name": "رياضيات 1",
    "share": 0.5,
    "weeks": "9 - 15"
   }
  },
  {
   "day": 3,
   "slots": [2, 3],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 3,
   "slots": [4, 5],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 3,
   "slots": [9],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 5,
   "slots": [0, 1, 2, 3],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 5,
   "slots": [4, 5],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  }],
 "gomaa-fahmy": [
  {
   "day": 1,
   "slots": [0, 1],
   "type": "lecture",
   "text": "محاضرة رياضيات 1 (مدرج 1)",
   "course": {
    "key": "external|رياضيات 1",
    "name": "رياضيات 1",
    "share": 0.5,
    "weeks": "1 - 7"
   }
  },
  {
   "day": 1,
   "slots": [6],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 2,
   "slots": [4, 5],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 2,
   "slots": [6, 7],
   "type": "lecture",
   "text": "محاضرة الات القوى الكهربية مدرج ميكانيكا",
   "course": {
    "key": "external|الات القوي الكهربيه",
    "name": "الات القوى الكهربية",
    "share": 0.5,
    "weeks": "9 - 15"
   }
  },
  {
   "day": 3,
   "slots": [4, 5],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [8],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 4,
   "slots": [0, 1],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 4,
   "slots": [4, 5],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 4,
   "slots": [7],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 4,
   "slots": [8, 9],
   "type": "office",
   "text": "ساعات مكتبية"
  }],
 "eman-awad": [
  {
   "day": 1,
   "slots": [0, 1],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 1,
   "slots": [4, 5],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 1,
   "slots": [6],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 2,
   "slots": [0, 1],
   "type": "lecture",
   "text": "محاضرة حاسبات وبرمجه مدرج 1",
   "course": {
    "key": "external|حاسبات وبرمجه",
    "name": "حاسبات وبرمجه",
    "share": 0.5,
    "weeks": "9 - 15"
   }
  },
  {
   "day": 2,
   "slots": [6, 7],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [4, 5],
   "type": "office",
   "text": "ساعات مكتبية"
  },
  {
   "day": 3,
   "slots": [8],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 4,
   "slots": [6, 7],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 4,
   "slots": [9],
   "type": "quality",
   "text": "جودة"
  }],
 "tamer-elsharkawy": [
  {
   "day": 1,
   "slots": [4, 5, 6],
   "type": "section",
   "text": "ت عملى معمل الالات القوى الكهربية 828",
   "course": {
    "key": "external|الات القوي الكهربيه",
    "name": "الات القوى الكهربية",
    "share": 1,
    "weeks": "1 - 15"
   }
  },
  {
   "day": 2,
   "slots": [5],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 3,
   "slots": [0, 1, 2, 3],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 3,
   "slots": [4, 5],
   "type": "quality",
   "text": "جودة"
  },
  {
   "day": 4,
   "slots": [4, 5],
   "type": "advising",
   "text": "ارشاد أكاديمي"
  },
  {
   "day": 4,
   "slots": [6, 7],
   "type": "quality",
   "text": "جودة"
  }]
};
