// Regenerates src/core/seedPresets.ts from the hand-made sheets in samples/expected:
//  - where each person's office hours, advising and quality sit (the committee's own choices);
//  - their lectures/labs in programmes whose master is still PDF-only (mechanics, preparatory).
//   node scripts/seed-from-samples.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readExpected } from '../src/core/compare.ts';
import { normalize } from '../src/core/normalize.ts';

const root = join(import.meta.dirname, '..');
const FILES: Record<string, string> = {
  'asmaa-radi': 'asmaa_radi', 'ahmed-salem': 'ahmed_salem', 'mai-helmy': 'mai_helmy', 'hend-elsayed': 'hend_elsayed',
  'ahmed-elsayed': 'ahmed_elsayed', 'asmaa-abdelrahim': 'asmaa_abdelrahim', 'mahmoud-elsadd': 'mahmoud_elsadd',
  'gomaa-fahmy': 'gomaa_fahmy', 'eman-awad': 'eman_awad', 'tamer-elsharkawy': 'tamer_elsharkawy_TA',
};
// Cells of the sheets that come from the mechanics / preparatory masters: `day:firstSlot` → course keyword.
const EXTERNAL: Record<string, Record<string, string>> = {
  'asmaa-radi': { '3:6': 'دوائر كهربيه والكترونيه' },
  'mai-helmy': { '3:6': 'دوائر كهربيه والكترونيه', '3:0': '', '3:8': '' },
  'mahmoud-elsadd': { '1:0': 'رياضيات 1' },
  'gomaa-fahmy': { '1:0': 'رياضيات 1', '2:6': 'الات القوي الكهربيه' },
  'asmaa-abdelrahim': { '2:0': 'حاسبات وبرمجه' },
  'eman-awad': { '2:0': 'حاسبات وبرمجه' },
  'ahmed-elsayed': { '2:6': 'الات القوي الكهربيه' },
  'tamer-elsharkawy': { '1:4': 'الات القوي الكهربيه' },
};
const DUTY_TEXT: Record<string, string> = { office: 'ساعات مكتبية', advising: 'ارشاد أكاديمي', quality: 'جودة' };
const tidy = (s: string) => s.replace(/ـ/g, '').replace(/\s+/g, ' ').trim();
const weeks = (w: string) => w.replace(/^(\d+)-(\d+)$/, (_, a, b) => (Number(a) < Number(b) ? `${a} - ${b}` : `${b} - ${a}`));

const out: Record<string, unknown[]> = {};
for (const [id, file] of Object.entries(FILES)) {
  const sheet = await readExpected(readFileSync(join(root, 'samples', 'expected', `${file}.xlsx`)));
  const items: { day: number; slots: number[]; type: string; text: string; course?: unknown }[] = [];
  for (let day = 0; day < 6; day++) {
    for (let slot = 0; slot < 10; slot++) {
      const cell = sheet.cells.get(`${day}:${slot}`);
      if (!cell) continue;
      const last = items[items.length - 1];
      if (last && last.day === day && last.slots[last.slots.length - 1] === slot - 1 && tidy(cell.text) === (last as { raw?: string }).raw) {
        last.slots.push(slot);
        continue;
      }
      const duty = cell.type === 'office' || cell.type === 'advising' || cell.type === 'quality';
      const keyword = EXTERNAL[id]?.[`${day}:${slot}`];
      if (!duty && keyword === undefined) {
        items.push({ day: -1, slots: [], type: '', text: '' }); // breaks a run
        continue;
      }
      const row = keyword ? sheet.courses.find((c) => normalize(c.name).includes(keyword)) : undefined;
      const item = { day, slots: [slot], type: cell.type, text: duty ? DUTY_TEXT[cell.type] : tidy(cell.text), raw: tidy(cell.text),
        course: row ? { key: `external|${keyword}`, name: tidy(row.name), share: row.share, weeks: weeks(row.weeks) } : undefined };
      items.push(item);
    }
  }
  out[id] = items.filter((it) => it.day >= 0).map(({ day, slots, type, text, course }) => ({ day, slots, type, text, ...(course ? { course } : {}) }));
}

writeFileSync(
  join(root, 'src', 'core', 'seedPresets.ts'),
  `// Generated by scripts/seed-from-samples.ts from samples/expected — do not edit by hand.
import type { Preset } from './roster.ts';

export const SEED_PRESETS: Record<string, Preset[]> = ${JSON.stringify(out, null, 1).replace(/\n\s+(?=\d|\])/g, ' ').replace(/\[ /g, '[').replace(/ \]/g, ']')};
`,
);
for (const [id, items] of Object.entries(out)) console.log(id, items.length, 'presets');
