// Regenerates src/core/seedStarts.ts: for every two-doctor lecture, who teaches weeks 1–7.
// Source: the masters in samples/masters plus the hand-corrected copies in samples/reference-docx
// (the client's working files often come without the underlines; these copies had them added).
//   node scripts/seed-starts.ts
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { nameKey } from '../src/core/normalize.ts';
import { readMaster } from '../src/core/pipeline.ts';
import { matchStaff, SEED_ROSTER } from '../src/core/roster.ts';
import { courseKey } from '../src/core/rules.ts';

const root = join(import.meta.dirname, '..');
const out: Record<string, string> = {};
for (const dir of ['samples/reference-docx', 'samples/masters']) {
  if (!existsSync(join(root, dir))) continue;
  for (const name of readdirSync(join(root, dir)).filter((f) => f.endsWith('.docx') || f.endsWith('.xlsx'))) {
    const master = await readMaster({ programme: name, name, data: readFileSync(join(root, dir, name)) });
    matchStaff(master.sessions, SEED_ROSTER);
    for (const s of master.sessions.filter((x) => x.parsed.type === 'lecture')) {
      const doctors = s.parsed.names.filter((t) => t.role === 'doctor');
      const marked = doctors.filter((t) => t.underline > 0.5);
      if (doctors.length === 2 && marked.length === 1) out[courseKey(s.parsed)] = marked[0].staffId ?? nameKey(marked[0].name);
    }
  }
}
const sorted = Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
writeFileSync(
  join(root, 'src', 'core', 'seedStarts.ts'),
  `// Generated by scripts/seed-starts.ts — do not edit by hand.
// course key → roster id (or name key) of the doctor who teaches weeks 1–7.
export const SEED_STARTS: Record<string, string> = ${JSON.stringify(sorted, null, 2)};
`,
);
console.log(Object.keys(sorted).length, 'courses');
